language: php

php:
  - '7.0'

install: composer install --dev
script: vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)

